### ISSUE TITLE
Git status doesn't populate

### ISSUE THREAD

**Issue by tnypxl** [SublimeGit/SublimeGit#108]
The following is the error I get when I run `Git: Status`.

```
KeyError: '#'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "SublimeGit/sgit/status.py", line 520, in run
  File "SublimeGit/sgit/status.py", line 120, in build_status
  File "SublimeGit/sgit/status.py", line 165, in build_files_status
```

Not sure what is causing it.

**Comment by MaxDaten** [comment]
Sorry for highjacking this issue but maybe I've got a related bug. I guess it is caused by files determined as 'copied' by git (shouldn't happen to often). This was my `git status --porcelain` from command line:
```
M  www/index.html
M  www/js/app.js
M  www/js/controllers.js
C  www/js/controllers.js -> www/js/library.js
M  www/js/services.js
```

The error in the Sublime Python console:
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
  File "SublimeGit/sgit/status.py", line 520, in run
  File "SublimeGit/sgit/status.py", line 118, in build_status
  File "SublimeGit/sgit/status.py", line 156, in build_files_status
KeyError: 'w'
```

- `git version 2.3.2 (Apple Git-55)`
- `You have SublimeGit 1.0.34`
