### ISSUE TITLE
git diff cached current file -- broken

### ISSUE THREAD

**Issue by drKnoxy** [SublimeGit/SublimeGit#167]
tosses this error in console:
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "SublimeGit/sgit/diff.py", line 123, in run
TypeError: run() missing 1 required positional argument: 'edit'
```

**Comment by michaelpedersen** [comment]
Nevemind, found the issue. It's fixed in 1.0.34
