### ISSUE TITLE
Git executable isn't found

### ISSUE THREAD

**Issue by yuvale** [SublimeGit/SublimeGit#170]
I'm using: Windows 7 64-bit, Sublime Text 2.0.2 (64-bit), SublimeGit 1.0.32 (installed using Package Control).

I'm having trouble getting SublimeGit to find the git executable.
Git is in this location on my machine: H:\Program Files (x86)\Git\bin.
This location is in my PATH environment variable, and I can run git from cmd.exe.

When I try to use SublimeGit, I get this message:

![image](https://cloud.githubusercontent.com/assets/2012892/5057590/e725086c-6cd1-11e4-9d27-25fde533b40c.png)

I tried all the options suggested in issue #55. Tried setting git_executables["git"] to "H:\Program Files (x86)\Git\bin", with forward slashes instead of backslashes, with short paths (H:/PROGRA~2/...), with/without trailing slash, with/without the executable name appended. Nothing works.
Also tried all of that directly in SublimeGit.sublime-settings instead of the user settings, just to be sure.

Following is my attempt at getting a little more information.

Using [Process Monitor](http://technet.microsoft.com/en-us/sysinternals/bb896645.aspx), I can see that no matter what I set git_executables to, Sublime only looks for git.exe in this path: C:\Program Files\git\bin\git.exe.
That path doesn't exist, it's not in my PATH, and I never had Git installed there. I also made sure it's nowhere in the Windows registry. So I'm guessing this is hard-coded somewhere in SublimeGit.

I can also see that the path I put in git_executable isn't searched. This is what I currently have in the settings (intentionally using a string that's easy to find in the log :)):

```
"log_level": "DEBUG",
"git_executables": {
    "git": ["blablabla"],
    "git_flow": ["blablabla"],
    "legit": ["blablabla"],
    "gitk": ["blablabla"]
},
```

As far as I can see from Process Monitor, Sublime Text never looks for that path.

Here's the console log for trying to run "git log":

```
[2014-11-15 14:29:41,112 - INFO     - SublimeGit.helpers] get_dir_from_view(view=30): C:\projects\project1
[2014-11-15 14:29:41,112 - INFO     - SublimeGit.helpers] get_repo(window=30, silent=True): C:\projects\project1 (file)
[2014-11-15 14:29:41,128 - DEBUG    - SublimeGit.cmd] cmd: [u'C:\\Program Files\\git\\bin\\git.exe', '--no-pager', '-c', 'color.diff=false', '-c', 'color.status=false', '-c', 'color.branch=false', '-c', 'status.displayCommentPrefix=true', '-c', 'core.commentchar=#', 'symbolic-ref', '-q', 'HEAD']
[2014-11-15 14:29:41,128 - INFO     - SublimeGit.helpers] get_dir_from_view(view=30): C:\projects\project1
[2014-11-15 14:29:41,128 - INFO     - SublimeGit.helpers] get_repo_from_window(window=8, silent=False): C:\projects\project1 (active file)
[2014-11-15 14:29:41,128 - DEBUG    - SublimeGit.cmd] cmd: [u'C:\\Program Files\\git\\bin\\git.exe', '--no-pager', '-c', 'color.diff=false', '-c', 'color.status=false', '-c', 'color.branch=false', '-c', 'status.displayCommentPrefix=true', '-c', 'core.commentchar=#', 'log', '--no-color', '--date=local', '--format=%s%x03%H%x03%an%x03%aE%x03%ad%x03%ar%x04']
error: Executable '['git']' was not found in PATH. Current PATH:

H
\Python27_32bit\;H
\Python27_32bit\Scripts;H
\Windows\system32;H
\Windows;H
\Windows\System32\Wbem;H
\Windows\System32\WindowsPowerShell\v1.0\;H
\Program Files (x86)\QuickTime\QTSystem\;H
\Program Files\nodejs\;H
\Program Files (x86)\SlikSvn\bin;H
\Program Files\Microsoft SQL Server\110\Tools\Binn\;H
\Program Files\FileBot\;H
\Program Files (x86)\nodejs\;H
\Users\yuval\AppData\Roaming\Python\Scripts;H
\Users\yuval\AppData\Roaming\npm;H
\Program Files (x86)\Git\bin

Try adjusting the git_executables['git'] setting.
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 339, in run_
  File "SublimeGit/sgit/log.py", line 32, in run
  File "SublimeGit/sgit/helpers.py", line 395, in get_quick_log
  File "SublimeGit/sgit/cmd.py", line 247, in git_string
  File "SublimeGit/sgit/cmd.py", line 90, in _string
  File "SublimeGit/sgit/cmd.py", line 159, in cmd
sgit2.cmd.SublimeGitException: Could not execute command: [Error 2] The system cannot find the file specified
[2014-11-15 14:29:42,329 - INFO     - SublimeGit.helpers] get_dir_from_view(view=30): C:\projects\project1
Exception in thread Thread-82:
Traceback (most recent call last):
  File ".\threading.py", line 532, in __bootstrap_inner
  File "SublimeGit/sgit/status.py", line 564, in run
  File "SublimeGit/sgit/cmd.py", line 247, in git_string
  File "SublimeGit/sgit/cmd.py", line 90, in _string
ValueError: need more than 2 values to unpack
```

Also, this message appears in the console whenever I switch between files:

```
[2014-11-15 14:36:29,138 - INFO     - SublimeGit.helpers] get_dir_from_view(view=71): C:\projects\project1
[2014-11-15 14:36:29,138 - INFO     - SublimeGit.helpers] get_repo(window=71, silent=True): C:\projects\project1 (file)
[2014-11-15 14:36:29,138 - DEBUG    - SublimeGit.cmd] cmd: [u'C:\\Program Files\\git\\bin\\git.exe', '--no-pager', '-c', 'color.diff=false', '-c', 'color.status=false', '-c', 'color.branch=false', '-c', 'status.displayCommentPrefix=true', '-c', 'core.commentchar=#', 'symbolic-ref', '-q', 'HEAD']
Exception in thread Thread-96:
Traceback (most recent call last):
  File ".\threading.py", line 532, in __bootstrap_inner
  File "SublimeGit/sgit/status.py", line 564, in run
  File "SublimeGit/sgit/cmd.py", line 247, in git_string
  File "SublimeGit/sgit/cmd.py", line 90, in _string
ValueError: need more than 2 values to unpack
```

**Comment by 4ndrej** [comment]
caused by removing folder with git repo while still having status window opened. Fixed in #259
