### ISSUE TITLE
Git pull & push not working in ST2 and throw exception

### ISSUE THREAD

**Issue by zanasmon** [SublimeGit/SublimeGit#177]
Hi,

I'm not able to use git pull and push. I checked from ST console and found this error. I used ST2 on OSX 10.9.5. 

Exception in thread Thread-7:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "SublimeGit/sgit/cmd.py", line 199, in async_inner
  File "SublimeGit/sgit/cmd.py", line 111, in env
  File "SublimeGit/sgit/util.py", line 144, in get_setting
  File "SublimeGit/sgit/util.py", line 140, in get_settings
RuntimeError: Must call on main thread, consider using sublime.set_timeout(function, timeout)

**Comment by michaelpedersen** [comment]
Yeah this is a ST2 specific issue. Will be fixed shortly... But you really should upgrade to ST3 :-)

**Comment by michaelpedersen** [comment]
Fixed in 1.0.34 which was just released.
