### ISSUE TITLE
Status line update doesn't work with yosemite fix in ST2

### ISSUE THREAD

**Issue by michaelpedersen** [SublimeGit/SublimeGit#193]
```
Exception in thread Thread-23:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "SublimeGit/sgit/status.py", line 562, in run
  File "SublimeGit/sgit/cmd.py", line 264, in git_string
  File "SublimeGit/sgit/cmd.py", line 90, in _string
  File "SublimeGit/sgit/cmd.py", line 144, in cmd
  File "SublimeGit/sgit/cmd.py", line 110, in env
  File "SublimeGit/sgit/util.py", line 144, in get_setting
  File "SublimeGit/sgit/util.py", line 140, in get_settings
RuntimeError: Must call on main thread, consider using sublime.set_timeout(function, timeout)

Exception in thread Thread-24:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "SublimeGit/sgit/status.py", line 562, in run
  File "SublimeGit/sgit/cmd.py", line 264, in git_string
  File "SublimeGit/sgit/cmd.py", line 90, in _string
  File "SublimeGit/sgit/cmd.py", line 144, in cmd
  File "SublimeGit/sgit/cmd.py", line 110, in env
  File "SublimeGit/sgit/util.py", line 144, in get_setting
  File "SublimeGit/sgit/util.py", line 140, in get_settings
RuntimeError: Must call on main thread, consider using sublime.set_timeout(function, timeout)

startup cache, total files: 256 cache hits: 256
startup time: 0.884844 (package setup was not run)
Exception in thread Thread-25:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "SublimeGit/sgit/status.py", line 562, in run
  File "SublimeGit/sgit/cmd.py", line 264, in git_string
  File "SublimeGit/sgit/cmd.py", line 90, in _string
  File "SublimeGit/sgit/cmd.py", line 144, in cmd
  File "SublimeGit/sgit/cmd.py", line 110, in env
  File "SublimeGit/sgit/util.py", line 144, in get_setting
  File "SublimeGit/sgit/util.py", line 140, in get_settings
RuntimeError: Must call on main thread, consider using sublime.set_timeout(function, timeout)

loaded 896 snippets
Package Control: Skipping automatic upgrade, last run at 2015-03-16 13:47:19, next run at 2015-03-16 14:47:19 or after
Exception in thread Thread-28:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "SublimeGit/sgit/status.py", line 562, in run
  File "SublimeGit/sgit/cmd.py", line 264, in git_string
  File "SublimeGit/sgit/cmd.py", line 90, in _string
  File "SublimeGit/sgit/cmd.py", line 144, in cmd
  File "SublimeGit/sgit/cmd.py", line 110, in env
  File "SublimeGit/sgit/util.py", line 144, in get_setting
  File "SublimeGit/sgit/util.py", line 140, in get_settings
RuntimeError: Must call on main thread, consider using sublime.set_timeout(function, timeout)

Writing file /Users/tdhopper/repos/qadium/posterior/distributions/distributions/dbg/models/nn.py with encoding UTF-8
Exception in thread Thread-29:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "SublimeGit/sgit/status.py", line 562, in run
  File "SublimeGit/sgit/cmd.py", line 264, in git_string
  File "SublimeGit/sgit/cmd.py", line 90, in _string
  File "SublimeGit/sgit/cmd.py", line 144, in cmd
  File "SublimeGit/sgit/cmd.py", line 110, in env
  File "SublimeGit/sgit/util.py", line 144, in get_setting
  File "SublimeGit/sgit/util.py", line 140, in get_settings
RuntimeError: Must call on main thread, consider using sublime.set_timeout(function, timeout)

Writing file /Users/tdhopper/repos/qadium/posterior/distributions/distributions/dbg/models/nn.py with encoding UTF-8
Exception in thread Thread-30:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "SublimeGit/sgit/status.py", line 562, in run
  File "SublimeGit/sgit/cmd.py", line 264, in git_string
  File "SublimeGit/sgit/cmd.py", line 90, in _string
  File "SublimeGit/sgit/cmd.py", line 144, in cmd
  File "SublimeGit/sgit/cmd.py", line 110, in env
  File "SublimeGit/sgit/util.py", line 144, in get_setting
  File "SublimeGit/sgit/util.py", line 140, in get_settings
RuntimeError: Must call on main thread, consider using sublime.set_timeout(function, timeout)
```

**Comment by tdhopper** [comment]
What's the status of this? Frustrating for a bug like this to linger in paid software.
