### ISSUE TITLE
KeyError: 'h' when staging files for commit

### ISSUE THREAD

**Issue by dylanfisher** [SublimeGit/SublimeGit#196]
I've gotten this error, or similar, a number of times when trying to stage a commit, which prevents the file from being staged. Staging and committing with terminal usually fixes the problem, though at some point the issue comes back. I can't reliably reproduce the issue. 

SublimeGit 1.0.34

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
  File "SublimeGit/sgit/status.py", line 520, in run
  File "SublimeGit/sgit/status.py", line 118, in build_status
  File "SublimeGit/sgit/status.py", line 156, in build_files_status
KeyError: 'h'
```

**Comment by gserrg** [comment]
`git version 2.17.1`
I have 
```
Untracked files:
www/images/_p_warning.png
Staged changes:
Modified   www/images/p_warning.png
```
`git status --porcelain` show
```
M  www/images/p_warning.png
?? www/images/_p_warning.png
```
after `git add www/images/_p_warning.png` i have this error. `git status`:
```
copied:     www/images/p_warning.png -> www/images/_p_warning.png
```
`git status --porcelain` show
```
C  www/images/p_warning.png -> www/images/_p_warning.png
```
`/usr/bin/git --no-pager -c color.diff=false -c color.status=false -c color.branch=false -c status.displayCommentPrefix=true -c core.commentchar=# status -z` have

```
...
C  www/images/_p_warning.pngwww/images/p_warning.pngA  www/images/bg-slider-pages.png
...
```
in https://github.com/SublimeGit/SublimeGit/blob/9c134c0baf000715929103dcb7d81b4caf2868f9/sgit/cmd.py#L107 `stdout` have
```
...
C  www/images/_p_warning.png\x00www/images/p_warning.png\x00A  www/images/bg-slider-pages.png\x00
...
```
in https://github.com/SublimeGit/SublimeGit/blob/9c134c0baf000715929103dcb7d81b4caf2868f9/sgit/helpers.py#L318 `print(status, filename)` show
```
C  www/images/_p_warning.png
ww /images/p_warning.png
```

====================
Conclusion: `git status -z` for copied files replace `->` to `x00` and in parse row after `C` required miss.

**Comment by gserrg** [comment]
for fix https://github.com/SublimeGit/SublimeGit/blob/9c134c0baf000715929103dcb7d81b4caf2868f9/sgit/helpers.py#L319 modify to `if status[0] == 'R' or status[0] == 'C':`
