### ISSUE TITLE
Git: Status error

### ISSUE THREAD

**Issue by abudarevsky** [SublimeGit/SublimeGit#237]
Hi,

When I installed the plugin for the first time it was working apart from that commands in command list were doubled like: Git: Status Git: Status.

Doing simple things I got it crashed and now it does not work even I removed the plugin and installed again.
Sublime 3126. Plugin from repository installed via sublime package manager

Package Control: Skipping automatic upgrade, last run at 2017-06-17 14:02:18, next run at 2017-06-17 15:02:18 or after
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "sgit.status in /Users/abudarevsky/Library/Application Support/Sublime Text 3/Installed Packages/SublimeGit.sublime-package", line 520, in run
  File "sgit.status in /Users/abudarevsky/Library/Application Support/Sublime Text 3/Installed Packages/SublimeGit.sublime-package", line 118, in build_status
  File "sgit.status in /Users/abudarevsky/Library/Application Support/Sublime Text 3/Installed Packages/SublimeGit.sublime-package", line 156, in build_files_status
KeyError: 'r'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "sgit.status in /Users/abudarevsky/Library/Application Support/Sublime Text 3/Installed Packages/SublimeGit.sublime-package", line 520, in run
  File "sgit.status in /Users/abudarevsky/Library/Application Support/Sublime Text 3/Installed Packages/SublimeGit.sublime-package", line 118, in build_status
  File "sgit.status in /Users/abudarevsky/Library/Application Support/Sublime Text 3/Installed Packages/SublimeGit.sublime-package", line 156, in build_files_status
KeyError: 'r'

**Comment by rjp2525** [comment]
+1, same issue here. Also running 3126

**Comment by khty2000** [comment]
me too。 i am 3143

**Comment by gserrg** [comment]
show #196
